export default {
  GUIDE_LOADED: 'GUIDE_LOADED',
  GUIDE_LOAD_FAILED: 'GUIDE_LOAD_FAILED',
  CHANNEL_CHANGED: 'CHANNEL_CHANGED',
  TUNE_FAILED: 'TUNE_FAILED',
  POWERED_ON: 'POWERED_ON',
  POWER_ON_ERROR: 'POWER_ON_ERROR',
  POWERED_OFF: 'POWERED_OFF',
  POWER_OFF_ERROR: 'POWER_OFF_ERROR',
  MUTE_STATE_CHANGED: 'MUTE_STATE_CHANGED',
  MUTE_ERROR: 'MUTE_ERROR'
};
